---
# yaml-language-server: $schema=https://raw.githubusercontent.com/mamba-org/conda-lock/main/conda_lock/schemas/environment.yaml
channels:
  - conda-forge
  - bioconda
dependencies:
  - curl=8.1.2
